1. 导入 pandas，用字典创建 DataFrame：

   name: Tom, Jerry, Mike

   score: 85, 92, 78

   gender: 男，女，男

In [26]:
import pandas as pd
df = pd.DataFrame({
    'name': ['Tom', 'Jerry', 'Mike'], 'score': [85, 92, 78],'gender': ['男', '女', '男']
})
df

    name  score gender
0    Tom     85      男
1  Jerry     92      女
2   Mike     78      男

##### series针对一维，如果没有特意写索引，默认为数字，从0开始，若写了索引（不一定是数字）就按照写的索引输出；DataFrame针对多维，索引一定要用''括起来，并且整个数据要用{}

2. 查看上述 DataFrame 的前 1 行、形状、列名、数据类型。

In [29]:
result = df.head(1)
result

  name  score gender
0  Tom     85      男

##### 获得前几行 head，获得后几行tail

##### 获取表中单个数据有两种方法，分别为索引标签、位置，索引标签要加''；若拿多个位置，第一种看成数组，用[,,,]，第二种用切片（位置索引、索引标签），用，是获取单个，：是切片获取多个；布尔型：ser_obj > 20 判断true or false ；ser_obj[ser_obj > 20] 获取对应true位置的数据

3. 用列表创建 DataFrame：

   data = [[1, "A"], [2, "B"], [3, "C"]]

   列名设为 id、tag

In [8]:
import pandas as pd
df = pd.DataFrame(data=[[1, "A"], [2, "B"], [3, "C"]], columns=['id', 'tag'])
df

   id tag
0   1   A
1   2   B
2   3   C

### 二、列与行操作

1. 选取 score 和 gender 两列。

   

2. 选取索引 0、2 的行。

   

3. 筛选 score>80 的行。

   

4. 新增一列 grade：score≥90 为优秀，否则为良好。

   

5. 删除 gender 列。

In [12]:
#设置一组数据
import pandas as pd
df = pd.DataFrame(data=[['张一',89,'男'],['里尔',98,'女'],['汪叁',76,'男']], columns=['name','score','gender'])
df

  name  score gender
0   张一     89      男
1   里尔     98      女
2   汪叁     76      男

In [18]:
result=df[['score','gender']]
result#在使用第一种方法创建数据时，选数据不能用第二种数据创建时用的读取数据方法

   score gender
0     89      男
1     98      女
2     76      男

In [19]:
#创建数据的第二种方法
import pandas as pd
df_2=pd.DataFrame({'name': ['张一', '里尔', '汪叁'], 'score': [89, 98, 76], 'gender': ['男', '女', '男']})
df_2 #使用这种创建数据的方法，两种读取数据的方式都可以使用

  name  score gender
0   张一     89      男
1   里尔     98      女
2   汪叁     76      男

In [22]:
df_2[['score','gender']]

   score gender
0     89      男
1     98      女
2     76      男

In [23]:
result=df_2[['score','gender']]
result

   score gender
0     89      男
1     98      女
2     76      男

In [28]:
df_2[df_2['score']>80]

  name  score gender
0   张一     89      男
1   里尔     98      女

In [34]:
import numpy as np
df['grade']=np.where(df['score']>90,'优秀','良好')
df

  name  score gender grade
0   张一     89      男    良好
1   里尔     98      女    优秀
2   汪叁     76      男    良好

In [35]:
df_2['grade']=df_2['score'].apply(lambda x: '优秀' if x > 90 else '良好')
df_2

  name  score gender grade
0   张一     89      男    良好
1   里尔     98      女    优秀
2   汪叁     76      男    良好

In [36]:
df.drop(columns=['gender'])

  name  score grade
0   张一     89    良好
1   里尔     98    优秀
2   汪叁     76    良好

### 三、缺失值

1. 创建含缺失值的 DataFrame：

   data = {"x":[1, None, 3], "y":[None, 5, 6]}

   检测缺失值并统计每列缺失数量。

   

2. 用 0 填充缺失值；删除含缺失值的行。

In [45]:
import pandas as pd 
df=pd.DataFrame( data = {"x":[1, None, 3], "y":[None, 5, 6]})
df

     x    y
0  1.0  NaN
1  NaN  5.0
2  3.0  6.0

In [46]:
result=pd.isnull(df)
result

       x      y
0  False   True
1   True  False
2  False  False

In [43]:
result.sum()

x    1
y    1
dtype: int64

In [47]:
df.fillna(0)

     x    y
0  1.0  0.0
1  0.0  5.0
2  3.0  6.0

In [49]:
df.dropna()

     x    y
2  3.0  6.0

### 四、分组聚合

1. 按 gender 分组，求 score 的均值和最大值。

   

2. 按 gender 分组，统计每组人数。

In [58]:
import pandas as pd
df = pd.DataFrame(data=[['张一',89,'男'],['里尔',98,'女'],['汪叁',76,'男']], columns=['name','score','gender'])
df

  name  score gender
0   张一     89      男
1   里尔     98      女
2   汪叁     76      男

In [60]:
df.groupby('gender')['score'].agg(['mean','max'])

        mean  max
gender
女       98.0   98
男       82.5   89

In [61]:
df.groupby('gender').size()

gender
女    1
男    2
dtype: int64

### 五、排序与去重

1. 按 score 升序排序。

   

2. 给 DataFrame 添加一行重复数据（如 Tom,85, 男），去重。

In [62]:
import pandas as pd
df = pd.DataFrame(data=[['张一',89,'男'],['里尔',98,'女'],['汪叁',76,'男']], columns=['name','score','gender'])
df

  name  score gender
0   张一     89      男
1   里尔     98      女
2   汪叁     76      男

In [65]:
df_sorted=df.sort_values(by='score',ascending=True)
df_sorted

  name  score gender
2   汪叁     76      男
0   张一     89      男
1   里尔     98      女

##### 按升序 ascending=True,按降序 ascending=False

In [66]:
new_df=pd.DataFrame(data=[['张一',89,'男']], columns=['name','score','gender'])
new_df

  name  score gender
0   张一     89      男

In [67]:
df=pd.concat([df,new_df],ignore_index=True)
df

  name  score gender
0   张一     89      男
1   里尔     98      女
2   汪叁     76      男
3   张一     89      男

In [69]:
df.duplicated()

0    False
1    False
2    False
3     True
dtype: bool

In [70]:
df.drop_duplicates()

  name  score gender
0   张一     89      男
1   里尔     98      女
2   汪叁     76      男


### 六、合并与拼接

1. 横向合并：

   df1 = pd.DataFrame ({"id":[1,2], "name":["X","Y"]})

   df2 = pd.DataFrame ({"id":[1,2], "age":[20,30]})

   按 id 合并。

   

2. 纵向拼接：

   df_a = pd.DataFrame ({"val":[1,2]})

   df_b = pd.DataFrame ({"val":[3,4]})

   拼接后重置索引。

In [71]:
import pandas as pd
df1 = pd.DataFrame ({"id":[1,2], "name":["X","Y"]})

df2 = pd.DataFrame ({"id":[1,2], "age":[20,30]})
df1,df2

(   id name
 0   1    X
 1   2    Y,
    id  age
 0   1   20
 1   2   30)

In [73]:
result=pd.concat([df1,df2],join='outer',axis=1)
result

   id name  id  age
0   1    X   1   20
1   2    Y   2   30

In [85]:
import pandas as pd
df_a = pd.DataFrame ({"val":[1,2]})
df_b = pd.DataFrame ({"val":[3,4]})
result=pd.concat([df_a,df_b],axis=0,ignore_index=True)
result

   val
0    1
1    2
2    3
3    4

### 七、时间处理

1. 创建时间列：["2025-01-01","2025-01-02","2025-01-03"]，转为 datetime 格式。

   

2. 提取时间列的月份、星期。

In [91]:
import pandas as pd
time_list = ['2025-01-01', '2025-01-02', '2025-01-03']
time_series = pd.to_datetime(time_list)
time_series

DatetimeIndex(['2025-01-01', '2025-01-02', '2025-01-03'], dtype='datetime64[us]', freq=None)

In [92]:
month = time_series.month
weekday = time_series.weekday
month,weekday

(Index([1, 1, 1], dtype='int32'), Index([2, 3, 4], dtype='int32'))

### 八、高级操作

1. 对 score 列做标准化（(值 - 均值)/ 标准差）。

   

2. 用透视表：行是 gender，值是 score，聚合函数为中位数。

In [93]:
import pandas as pd
df = pd.DataFrame({
    'name': ['Tom', 'Jerry', 'Mike'], 'score': [85, 92, 78],'gender': ['男', '女', '男']
})
df

    name  score gender
0    Tom     85      男
1  Jerry     92      女
2   Mike     78      男

In [95]:
df['score_std'] = (df['score'] - df['score'].mean()) / df['score'].std()
df

    name  score gender  score_std
0    Tom     85      男        0.0
1  Jerry     92      女        1.0
2   Mike     78      男       -1.0

In [96]:
pivot_result = df.pivot_table(
    index='gender',
    values='score',
    aggfunc='median'
)
pivot_result

        score
gender
女        92.0
男        81.5